export const pizzas = [
  {
    id: 1,
    name: "Margherita",
    category: "vegetarian",
    ingredients: ["Tomato", "Mozzarella", "Basil"],
    price: 12.99,
    image: "/images/margherita.jpg",
    count: 1,
  },
  {
    id: 2,
    name: "Pepperoni",
    category: "meat",
    ingredients: ["Pepperoni", "Cheese", "Tomato sauce"],
    price: 15.99,
    image: "/images/pepperoni.jpg",
    count: 1,
  },
  {
    id: 3,
    name: "Chicken BBQ",
    category: "meat",
    ingredients: ["Chicken", "BBQ sauce", "Onion"],
    price: 16.99,
    image: "/images/bbq.jpg",
    count: 1,
  },
  {
    id: 4,
    name: "Sea Pizza",
    category: "sea",
    ingredients: ["Shrimp", "Squid", "Cheese"],
    price: 18.99,
    image: "/images/sea.jpg",
    count: 1,
  },
  {
    id: 5,
    name: "Mushroom Delight",
    category: "vegetarian",
    ingredients: ["Mushroom", "Mozzarella", "Cream sauce"],
    price: 13.5,
    image: "/images/mushroom.jpg",
    count: 1,
  },
  {
    id: 6,
    name: "Spicy Beef",
    category: "meat",
    ingredients: ["Beef", "Chili", "Cheese", "Onion"],
    price: 17.25,
    image: "/images/beef.jpg",
    count: 1,
  },
  {
    id: 7,
    name: "Four Cheese",
    category: "vegetarian",
    ingredients: ["Mozzarella", "Cheddar", "Parmesan", "Gorgonzola"],
    price: 14.99,
    image: "/images/four-cheese.jpg",
    count: 1,
  },
  {
    id: 8,
    name: "Shrimp Special",
    category: "sea",
    ingredients: ["Shrimp", "Garlic", "Cheese", "Lemon"],
    price: 19.5,
    image: "/images/shrimp.jpg",
    count: 1,
  },
];
